### ISSUE TITLE
Titles no longer render on 4.0.2

### ISSUE THREAD

**Issue by danconnell** [tim-evans/ember-page-title#118]
When upgrading from 4.0.1 to 4.0.2, this addon no longer works for us.

The issue is caused by the changes made here: https://github.com/tim-evans/ember-page-title/pull/117.

The existing title tag is removed by `_removeExistingTitleTag` after ember-cli-head has rendered it, and so it is never readded.

As I don't fully understand why this change was made, I'm not sure how to resolve it.

**Comment by buschtoens** [comment]
https://github.com/tim-evans/ember-page-title#post-install-cleanup

I had the same problem. You have to add the `<title>` tag back in for non-Fastboot apps.

**Comment by danconnell** [comment]
Yep, that fixed it. Thanks @buschtoens.

**Comment by tim-evans** [comment]
Thanks @buschtoens 😄
