### ISSUE TITLE
title no longer appearing in 4.0.3 (updated from 3.1.5)

### ISSUE THREAD

**Issue by efx** [tim-evans/ember-page-title#121]
Our app generates a page title from a computed that derives its value from a network call. It is not using fast-boot.
I updated our app to use 4.0.3, but now see the `<title>` element removed completely from the DOM.
`application.hbs` snippet:
```hbs
{{title
	(if timer 'Please Log In' appTitle)
	separator=" | "}}
```
The property that `appTitle` depends on intially is null, and so the computed returns an empty string. Once the network call succeeds, the `appTitle` computed returns with the proper value. I can mock this further in an example test.
Comparison of changes for quick reference: https://github.com/tim-evans/ember-page-title/compare/3.1.5...4.0.3

**Comment by tim-evans** [comment]
Did you read the changes for [4.0.0](https://github.com/tim-evans/ember-page-title/releases/tag/4.0.0) and update your `application.hbs`?

**Comment by tim-evans** [comment]
Sorry that you encountered this :/

**Comment by efx** [comment]
ah, thanks for the link. I did not update per those notes. I usually update via npm, and check the repo for changelog notes. I'll test this and close once I get a moment.

**Comment by tim-evans** [comment]
Thanks @efx 😄

**Comment by adamlc** [comment]
As I new user the I've just come across this issue, just need to update the docs 👍

**Comment by mkay581** [comment]
Yah, just got bit by this. We should definitely update the README instructions to ensure everyone knows to add the new `{{head-layout}}`. In my experience, devs who are installing this addon for the first time won't know to go and look at the releases page to find a required step.

**Comment by efx** [comment]
good idea @mkay581 , I just opened a PR. If y'all could read it and ensure it makes sense that would be great.

**Comment by efx** [comment]
verified in our app, closing.
