### ISSUE TITLE
Prepend by default true

### ISSUE THREAD

**Issue by ondrejsevcik** [tim-evans/ember-page-title#131]
Hi, I have a proposal. In a next major version, set prepend option by default to `true`. 

With a limited space to show in a page title, it's a best practice to put current page title first. Otherwise you end up with a title where you can't clearly see what page are you in. This is especially issue when you have nested pages with long titles.

**Comment by tim-evans** [comment]
Sound alright by me!

**Comment by tim-evans** [comment]
If you PR this, I'm more than happy to merge and get this released

**Comment by tim-evans** [comment]
Done!
