### ISSUE TITLE
loading route overtakes page title in browser history

### ISSUE THREAD

**Issue by brenna** [tim-evans/ember-page-title#22]
If a route hits a `loading` sub-state before render, the browser history keeps the loading route's title, *not* the route's eventual title. The `<title>` tag is eventually updated with the correct page title but history only remembers the initial title from the loading route. 

This is problematic when using a catch-all top-level `loading` route.

**Comment by tim-evans** [comment]
That's tricky. I'm not sure that anything can be done about this in the addon- this may be something to discuss with the core team. There's also the possibility of doing the following with your routes:

```javascript
this.route('peanuts', function () {
  // {{title}} helper here
  this.route('peanutsIndex', { path: '/' }, function () {
    // Loading and error state here
  });
});
```

**Comment by brenna** [comment]
Ah yep, that was my solution too, but was trying to avoid  the awkward `index/index/` for the top-level index route. 

I think core's solution of allowing `index-loading` style loading routes would also alleviate, but I'm a version behind that feature.

Thanks!

**Comment by tim-evans** [comment]
My pleasure!
