### ISSUE TITLE
There's no title until the whole ember app is loaded

### ISSUE THREAD

**Issue by ivanvotti** [tim-evans/ember-page-title#28]
The [README](https://github.com/tim-evans/ember-page-title/blob/master/README.md) says: `For proper functioning you will need to remove the default <title> tag from app/index.html.`

If you don't use FastBoot, it will introduce a delay. The page will have no title until the whole ember app is loaded.

**Comment by ronco** [comment]
@ivanvotti Good point.  I think we can probably come up with a solution here with an initializer to rip out the pre-existing title tag when we attach the dynamic title.

**Comment by bladnman** [comment]
Big bump here.

**Comment by tim-evans** [comment]
@ronco any ideas on this?

**Comment by ronco** [comment]
I've got an idea for a brute force solution that could work until I come up with something more elegant.  We could have a browser only initializer remove the pre-existing `<title>` tag.  Then non-fastboot builds get the initial title during app load, and then dynamic title after app load.  Fastboot users would still need to remove `<title>` manually from their index.html.  Let me know if you're interested in that as a solution for now.

**Comment by tim-evans** [comment]
Other folks here ok with this? ^^

**Comment by ronco** [comment]
We just had a lengthy discussion of this issue in the Fastboot weekly meeting.  We'll be working on a better universal solution for this problem.  I'll keep you updated as it develops.

**Comment by tim-evans** [comment]
Thanks for the update ❤️

**Comment by tim-evans** [comment]
Hi @ronco! Any updates from the fastboot team?

**Comment by ronco** [comment]
@rwjblue Do you have any updates on the ember-cli-head plans and using it in non-fastboot environments?

**Comment by lolmaus** [comment]
Why must static `<title>` be removed? Can the static title be displayed while the app loads and then replaced by a dynamic one with `ember-page-title`?

**Comment by timhaines** [comment]
@tim-evans What do you recommend as best practice around this at the moment?  We're not using fastboot and would like the initial html to include a title - that can be updated after the ember app's loaded.

**Comment by tim-evans** [comment]
@timhaines I have a spike to remove the title from the dom before the service initializes. I'm not sure if that's the best solution, but will take PRs.

**Comment by fotinakis** [comment]
@tim-evans if we made a PR that added an instance-initializer which did something like `Ember.$.remove('title')`, would that be what you're looking for?

**Comment by tim-evans** [comment]
Yeah, that should work!
