### ISSUE TITLE
Set default values for `separator` and `prepend` with `config/environment.js`

### ISSUE THREAD

**Issue by ivanvotti** [tim-evans/ember-page-title#29]
It would be great if we can set default settings for the addon with `config/environment.js`, like so:

```
  pageTitle: {
    separator: ' | ',
    prepend: true
  }
```

It is a standard Ember way of addon configuration. It's really not common to setup an addon  by extending its service.

**Comment by robclancy** [comment]
Yes please, this is really weird not doing this from the start.

**Comment by tim-evans** [comment]
Could you elaborate this? You don't actually need to extend the service to change the default `separator` / `prepend` attributes; you can do this by setting it on the root `{{title}}` helper:

```hbs
{{title "Kittez" separator=" ~ " prepend=true}}
```

**Comment by robclancy** [comment]
Which is the way I have done it now after looking at the code. Your documentation says to override the service which doesn't even allow setting the default prepend anyway. Why not just document the root `{{title}}` setting it to default but also allow to configure using normal configuration?

Our issue now is we don't like the nesting. So if you could default it to replace it would be great or we are just going to fork / do our own implementation. Also is being able to do `{{#title}} {{/title}}` ever going to be possible? We have to use concat a lot now which gets a little messy.

If you are open to these things I could make pull requests when we get to them on our projects (which could be many weeks away).

**Comment by buschtoens** [comment]
@robclancy the block form won't be possible, as `{{title}}` is a helper, not a component. 

As to the replace thingy: you'd either have to `replace=true` everywhere or maybe use `ember-cli-head` directly, if that fits your use case better. There's also `ember-cli-document-title`.

**Comment by tim-evans** [comment]
@robclancy OH. I'll def fix the documentation, and possibly add a configuration for replace everywhere strategy. That's super valid.

**Comment by tim-evans** [comment]
Also, `concat` isn't necessary to use. I've made it so the helper concats automatically:

```hbs
{{title "Hello, " person.name "!"}}
```

**Comment by tim-evans** [comment]
This is in release 3.0.2

**Comment by ivanvotti** [comment]
It works. Thank you.
