### ISSUE TITLE
head.hbs template cannot be customized

### ISSUE THREAD

**Issue by vlascik** [tim-evans/ember-page-title#30]
Trying to create custom `app/templates/head.hbs` results in 
`The Broccoli Plugin: [BroccoliMergeTrees: addonPreprocessTree(template)] failed with:
Error: Merge error: file project/templates/head.hbs exists in ..\tmp\broccoli_merge_trees-input_base_path-sznru7ev.tmp\0 and ..\tmp\broccoli_merge_trees-input_base_path-sznru7ev.tmp\1
Pass option { overwrite: true } to mergeTrees in order to have the latter file win.
    at BroccoliMergeTrees._mergeRelativePath 
`

**Comment by tim-evans** [comment]
If you have a change @ronco, do you have an idea of what's going on here?

**Comment by ronco** [comment]
Hi @vlascik, what version of ember-cli & ember are you using?  Is the `app/templates/head.hbs` you're using coming from your own app, or are you having a conflict between addons?

**Comment by vlascik** [comment]
ember+cli is at 2.4.2. `head.hbs` is coming from my app, if I remove it, it compiles fine. 
page-title is included in addon that i use in my apps to share code, in dependencies hash, instead of devDependencies.

**Comment by ronco** [comment]
Oh I see.  I think the issue is arising from from the nested addon & dependencies hash.  Direct app consumption of this addon works fine with a custom `head.hbs`.  I'm going to try to get a similar setup going that recreates this error.  I'll let you know when I have more info.

**Comment by ronco** [comment]
@vlascik I'm having difficulty recreating this issue.  Initially I had difficulty getting an addon to wrap this addon properly.  When I included in in the dependencies hash of the wrapping addon I got this in app builds:
```
Cannot read property 'registry' of undefined
TypeError: Cannot read property 'registry' of undefined
    at Class.module.exports.included (/Users/ronco/github/page-title-consumer/node_modules/page-title-wrapper/node_modules/ember-page-title/index.js
:12:13)
    at /Users/ronco/github/page-title-consumer/node_modules/ember-cli/lib/models/addon.js:244:32
    at Array.map (native)
    at Class.eachAddonInvoke (/Users/ronco/github/page-title-consumer/node_modules/ember-cli/lib/models/addon.js:242:22)
    at Class.Addon.included (/Users/ronco/github/page-title-consumer/node_modules/ember-cli/lib/models/addon.js:349:8)
    at EmberApp.<anonymous> (/Users/ronco/github/page-title-consumer/node_modules/ember-cli/lib/broccoli/ember-app.js:413:15)
    at Array.filter (native)
    at EmberApp._notifyAddonIncluded (/Users/ronco/github/page-title-consumer/node_modules/ember-cli/lib/broccoli/ember-app.js:408:45)
    at new EmberApp (/Users/ronco/github/page-title-consumer/node_modules/ember-cli/lib/broccoli/ember-app.js:106:8)
    at module.exports (/Users/ronco/github/page-title-consumer/ember-cli-build.js:6:13)
```

Did you run into this?  I think that's a valid separate issue I'll file.

I was able to hack that to work by actually editing `index.js` in my copy of `ember-page-title` and at that point everything worked while having a `head.hbs` template in the end app.

Is there anything else at play here that could be contributing to the issue?  Do you have a `head.hbs` in your wrapping addon?

**Comment by vlascik** [comment]
yeah I hacked it as well, @tim-evans should change index.js to something like:  
```
included: function (app) {
    this._super.included.apply(this, arguments);

    if (app.app) {
      app = app.app;
    }
    this.app = app;
```
i was about to file that as well.
Hm, no, I don't have head.hbs in my addon, just in app, I'll try to look if some other addon doesn't use ember-cli-head, or I'll just run build through debugger. I'll let you know.

**Comment by ronco** [comment]
Addon consumption issue filed with #31

**Comment by vlascik** [comment]
So, no other addon uses cli-head, it's just my addon via page-title, but it doesn't work if i include page-title directly in app either. However, it works if I include just the cli-head into both app and addon. Did you try it with cli-head or page-title?
I tried to run it through debugger, but there isn't really anything else to know, it's just a conflict on app/templates/head.hbs from app and cli-head. Maybe the correct way to include head.hbs would be instead to generate it from blueprint into the consuming app? That way it would just be added to app/templates and there would be no conflict.

**Comment by ronco** [comment]
Hmm.  I'm stumped.  My best guess is there's a difference in one of the broccoli or ember-cli related dependencies that's breaking down with this behavior.  I've pushed up my test wrapper [addon](https://github.com/ronco/page-title-wrapper/blob/master/package.json) (with a hacked copy of [ember-page-title](https://github.com/ronco/ember-page-title/blob/addon-hack/index.js)) and [app](https://github.com/ronco/page-title-consumer/blob/nested-addon-bug/package.json) that are functioning.  You can compare their `package.json`s to see if something jumps out.

**Comment by vlascik** [comment]
@ronco: So I tried your app, it worked fine, then I noticed you use ember-cli 2.3.0, I used 2.4.2. When I tried to change your sample app to 2.4.2, the same error as in my app happened. I guess there was some change in cli that causes this.
I'm going to try to update to the newest cli next.

**Comment by tim-evans** [comment]
Super :D
