### ISSUE TITLE
Separator added for null-titles

### ISSUE THREAD

**Issue by bladnman** [tim-evans/ember-page-title#33]
I have pages where the 'eventual' page title is inside of data pulls or other promises. This means that my page title looks like

```Sitename |```

While the resources load before becoming

```Sitename | Smile```

I think I'd prefer that segments with null (or at least undefined) are not added to the title array. It looks like this could be a small augmentation to the `toString` function if that's a direction this add-on is willing to go.

**Comment by tim-evans** [comment]
Agreed :)

**Comment by tim-evans** [comment]
Released in 3.0.1~
