### ISSUE TITLE
Doesn't work in latest release 3.0.2

### ISSUE THREAD

**Issue by erichonkanen** [tim-evans/ember-page-title#34]
Hello, this addon has stopped working for me when upgrading to 3.0.2 using ember 2.5.1
```
{{title "foo" separator=" | "}}
{{#app-main}}
  {{#left-nav showModal="showModal"}}{{/left-nav}}
  {{outlet}}
  {{outlet 'modal'}}
{{/app-main}}
```
doesnt show up but rather the title from my index.html file does

**Comment by tim-evans** [comment]
Oh, you'll need to remove your title tag from index.html as per the README notes. Sorry! We're working on a patch so you won't need to do this in future releases.

**Comment by erichonkanen** [comment]
ah that was it thanks!
