### ISSUE TITLE
Conflict with ember-cli-meta-tags

### ISSUE THREAD

**Issue by Crabar** [tim-evans/ember-page-title#35]
I tried to use **_ember-cli-meta-tags_** and _**ember-page-title**_ in same application, but looks like ember-page-title overrides ember-cli-head section and removes any meta tags added by ember-cli-meta-tags.

Is it possible to use both in same application?

I just want to add title and meta-description based on models to each route.

**Comment by tim-evans** [comment]
I think you may have to create a custom head.hbs that merges them both together 😅 
Could you confirm @ronco ?

**Comment by ronco** [comment]
Yes, a custom head.hbs in your app/templates directory can make this work. You'll want the contents from the app/templates/head.hbs in this repo and the one provided from ember-cli-meta-tags.

Now that I think about it this would be a nice optional blueprint ember-cli-meta-tags could provide. Let me know if merging them in your app namespace works and if so I'll add a blueprint to make it easier in the future.

**Comment by Crabar** [comment]
In my case I just had used **_ember-cli-head_** directly and had implemented all what I need. IMHO, it will be good to add something about head.hbs in addons' docs.

**Comment by tim-evans** [comment]
Yeeep.

**Comment by ronco** [comment]
Makes sense. I'll update docs on ember-cli-meta-tags in the next day. @tim-evans do you have ember-page-title covered or would you like a PR?

**Comment by tim-evans** [comment]
I can cover this.
