### ISSUE TITLE
Make it work with engines

### ISSUE THREAD

**Issue by mydea** [tim-evans/ember-page-title#38]
Hi,

I am trying out engines, and found out that this addon doesn't work in that scenario. First of all, it can't even be installed due to https://github.com/tim-evans/ember-page-title/issues/31. 

So I tried to circumvent this by basically disabling the {{title}} lookup in my engine with:

```js
if (typeof this.app !== 'undefined' && typeof this.app.registry !== 'undefined') {
  this.app.registry.add('htmlbars-ast-plugin', {
    name: 'translate-title-helper-to-page-title-helper',
    plugin: TranslateHelperName
  });
}
```

So I could just use `{{page-title}}` in the engine. But it still didn't work, because of the way ember-cli-head works.

So I got it to work with a few workarounds - which might also be interesting for anyone else trying this.

1.) Define the `header-data` and `page-title-list` services as dependencies.
2.) In the engine, create a component `head-content` with the following content:

```js
import Ember from 'ember';
import layout from 'my-host-app-name/templates/head';

const {
  inject,
  Component
} = Ember;

export default Component.extend({
  tagName: '',
  model: inject.service('head-data'),
  layout
});
```

3.) Now use `{{page-title}}` instead of `{{title}}` in your engine, and everything works!

Maybe this can somehow be simplified, or at least added to the readme. However, it depends on https://github.com/tim-evans/ember-page-title/issues/31 being fixed first, otherwise the app can't even load.

**Comment by tim-evans** [comment]
Merged! Anything else to do to make this work?

**Comment by mydea** [comment]
I use it in my app and it works fine so far - the docs should maybe be updated with the information to make this work in engines?

**Comment by tim-evans** [comment]
I've changed which hook the ast-plugin gets used. Could anyone check this out?

**Comment by mydea** [comment]
I tried it, I can use `{{title}}` now in my engine! Great! :)

**Comment by tim-evans** [comment]
Thanks for the confirmation 🎉  Sooo happy to have figured this out.

**Comment by mydea** [comment]
Just adding this here, if someone else runs in to this:

ember-cli-head broke my acceptance tests when using engines.

So I added 

```js
if (environment === 'test') {
  ENV['ember-cli-head'] = {
      suppressBrowserRender: true
  };
}
```

to my environment.js, which made it work again.
