### ISSUE TITLE
Ember CLI AST Caching Deprecation

### ISSUE THREAD

**Issue by SaladFork** [tim-evans/ember-page-title#42]
Using `ember-cli@2.7.0`:
> DEPRECATION: ember-cli-htmlbars is opting out of caching due to an AST plugin that does not provide a caching strategy: `translate-title-helper-to-page-title-helper`.

**Comment by tim-evans** [comment]
I saw that. Hmm... I'm not sure how to fix this.

**Comment by tim-evans** [comment]
I think I fixed it 🎉
