### ISSUE TITLE
Don't update page title until transition is complete

### ISSUE THREAD

**Issue by rlivsey** [tim-evans/ember-page-title#44]
When an app has loading sub-states between two routes the title updates twice - once to remove the current title & transitions to the parent title, then again when the transition is complete.

Eg.
- `/foos/bar` - "My App / Foos / Bar"
- `/foos/-loading` - "My App / Foos" <- don't want to see this one
- `/foos/baz` - "My App / Foos / Baz"

This might be rather tricky, but it would be nice if we could detect we're transitioning through a loading state and not update the title until the transition is complete.

**Comment by tim-evans** [comment]
I think that will have to wait until we have a router service to do so.

**Comment by tim-evans** [comment]
That way we can check if the router is loading rather than using private APIs to update

**Comment by jherdman** [comment]
@rlivsey is this resulting in the following deprecation warning for you?

```
ember.debug.js:6628 DEPRECATION: You modified pageTitle twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 3.0 [deprecation id: ember-views.render-double-modify]
```

**Comment by g5codyswartz** [comment]
@jherdman I am getting the deprecation warning 

Here's a quick and dirty watcher for the title changing: 
```
var lastTitle = document.title;
var interval = setInterval(function(){
  var title = document.title;
  if (lastTitle !== title){
    lastTitle = title; 
    console.log(title);
  }
}, 100);
```

**Comment by tim-evans** [comment]
@jherdman / @g5codyswartz could either of you open up an issue so I can track this warning?

**Comment by jherdman** [comment]
@tim-evans apologies for the slow reply. I'm not entirely sure where you'd like me to open the issue. Isn't this issue the correct place?

**Comment by tim-evans** [comment]
I found this being super annoying in our app, so I fixed it 🎉

**Comment by rlivsey** [comment]
Awesome, less code than I thought it would be too!

**Comment by jherdman** [comment]
I'm definitely finding this to be the case still in the 4.0 series too. I'm trying to display the top most title token on a page. Something like this:

```hbs
{{title 'Show me on the page'}}

<h1>{{pageTitleList.sortedTokens.lastObject.token}}</h1>
```

Transitioning routes will cause this error to happen still.
