### ISSUE TITLE
Not working in ember 2.11.2

### ISSUE THREAD

**Issue by erichonkanen** [tim-evans/ember-page-title#57]
Hello, I just noticed my page titles aren't working like they used to and not sure what's going on.. I have latest version of this package, also using ember-cli-meta-tags (not sure if that's a conflict)...

**Comment by tim-evans** [comment]
Do you have `<title>{{model.title}}</title>` in your `head.hbs`?

**Comment by erichonkanen** [comment]
👏 ah that fixed it! thank you sir

**Comment by tim-evans** [comment]
😁
